// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7yAuReHR9qgeD2Z7VNxLlaJGaJl4KG8',
    appId: '1:683619942788:web:b780e4f74d8ac46b021dd1',
    messagingSenderId: '683619942788',
    projectId: 'vehical-location-tracker',
    authDomain: 'vehical-location-tracker.firebaseapp.com',
    databaseURL: 'https://vehical-location-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'vehical-location-tracker.appspot.com',
    measurementId: 'G-X964BXN7PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2wpff_O3DEApb-ygeT22FxrWKrFJ9i0',
    appId: '1:683619942788:android:231bf68114c605a9021dd1',
    messagingSenderId: '683619942788',
    projectId: 'vehical-location-tracker',
    databaseURL: 'https://vehical-location-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'vehical-location-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvJdtuVpO7FIY4eO2vUFuNYds_J1Toztw',
    appId: '1:683619942788:ios:c8fbd64bfea289d6021dd1',
    messagingSenderId: '683619942788',
    projectId: 'vehical-location-tracker',
    databaseURL: 'https://vehical-location-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'vehical-location-tracker.appspot.com',
    iosBundleId: 'com.example.locationTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvJdtuVpO7FIY4eO2vUFuNYds_J1Toztw',
    appId: '1:683619942788:ios:2d2c901aa5a1f6e8021dd1',
    messagingSenderId: '683619942788',
    projectId: 'vehical-location-tracker',
    databaseURL: 'https://vehical-location-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'vehical-location-tracker.appspot.com',
    iosBundleId: 'com.example.locationTrackingApp.RunnerTests',
  );
}
